name: Fetch-submodule

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 2 * * *'

jobs:
  fetch_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
